---
title: "Untitled"
author: "Eva Reindl"
date: "19 11 2020"
output: word_document
---

#INFERENTIAL STATISTICS TRIAL BY TRIAL DATA

```{r}
#PREPARE
R.Version()
rm(list=ls())#removes any other items in your workspace

library(lme4)
library(tidyverse)
library(ggthemes)
source("./functions/diagnostic_fcns.r")
source("./functions/glmm_stability.r")
source("./functions/boot_glmm.r")
source("./functions/drop1_para.r")

load("shifting_tray_CI_calc.RData")

```

```{r}
#LOAD DATA
#setwd("C:\\")#sets the working directory, this is where your datafile is
TrayTask <-read.csv("data/Jess_FinalData.csv",header=TRUE, sep = ";")
```

```{r}
#OVERVIEW
str(TrayTask)

#recode variables
TrayTask$Age_group <- as.factor(TrayTask$Age)#this converts a variable classified as continuous into a categorical variable
levels(TrayTask$Age_group)

str(TrayTask)#check whether changes were implemented and if there are any outstanding issues
```

## Postswitch Phase
create a subset for postswitch data
```{r}
postswitch<-subset(TrayTask, Pre_or_postswitch == "post")

postswitch$z.age=as.vector(scale(postswitch$Age_months))#transform age to mean of 0 and SD of 1
mean(postswitch$z.age)#check whether it has worked
sd(postswitch$z.age)
```
```{r eval=FALSE, echo=FALSE}

postswitch$z.trial=scale(postswitch$Trialnr)
postswitch$Relevant_dimension.c= scale(as.numeric(postswitch$Relevant_dimension), scale = FALSE)
postswitch$Condition.c= scale(as.numeric(postswitch$Condition), scale = FALSE)

str(postswitch)
summary(postswitch)
xx.fe.re=fe.re.tab(fe.model="Success ~ z.age + Relevant_dimension + Condition + 
                      z.trial ",
                   re="(1|Subject_ID)", data=postswitch)
xx.fe.re$summary


```
```{r}
contr<-glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=10000000))
post.mod<-glmer(Success ~ (z.age+I(z.age^2)) * Relevant_dimension * Condition + 
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)

summary(post.mod)

drop1(post.mod, test = "Chisq")

```



```{r}
contr<-glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=10000000))
post.mod<-glmer(Success ~ ((z.age+I(z.age^2)) : Relevant_dimension : Condition)^2 + 
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)

summary(post.mod)

drop1(post.mod, test = "Chisq")

```



```{r}
contr<-glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=10000000))
post.mod<-glmer(Success ~ (z.age+I(z.age^2))*Condition + Relevant_dimension+
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)

summary(post.mod)

drop1(post.mod, test = "Chisq")

```

```{r}
contr<-glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=10000000))
post.mod<-glmer(Success ~ (z.age+I(z.age^2)) + Relevant_dimension + Condition + 
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)

summary(post.mod)

drop1(post.mod, test = "Chisq")

```

## Model for CIs
```{r}
post.mod_trialCI<-glmer(Success ~ (z.age+I(z.age^2)) + Relevant_dimension.c + Condition.c + 
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)
```

```{r}
post.mod_conCI<-glmer(Success ~ (z.age+I(z.age^2)) + Relevant_dimension.c + Condition + 
                      z.trial + 
                      (1+z.trial|Subject_ID), family = binomial, data=postswitch,control=contr)
```


```{r}
pred.trial.ci=boot.glmm.pred(model.res=post.mod_trialCI , resol=36, level=0.95, use="z.trial", n.cores="all-1", para=T)

pred.con.ci=boot.glmm.pred(model.res=post.mod_conCI ,  level=0.95, use="Condition", n.cores="all-1", para=T)
```

```{r}
postswitch.plot <- postswitch %>%
  group_by(Trialnr) %>% 
  summarize(correct= mean(Success))%>%
  ungroup()%>%
  group_by(Trialnr)%>%
    add_count(correct)

plot.trial=seq(from=min(postswitch.plot$Trialnr),
             to=max(postswitch.plot$Trialnr),length.out=36)

ci.data<-pred.trial.ci$ci.predicted 

trial.plot<-ggplot(data=ci.data, aes(y=fitted))+
   #geom_point(data = postswitch.plot, aes(x=Trialnr, y=correct), size=postswitch.plot$n)+
    geom_ribbon(data = ci.data, aes(x = plot.trial, y = fitted, ymin = lower.cl, ymax = upper.cl), fill = "grey", alpha = 0.5) +
  geom_line(data = ci.data, aes(x = plot.trial, y = fitted), lty = 2)+
  theme_few()+ylab("Probability of success")+xlab("Trial number")+ylim(0,1)

ggsave(trial.plot, filename="graphs/trial_plot.png", height=5, width=6, scale=0.7)
```
```{r}
postswitch.agg <- postswitch %>%
  group_by(Subject_ID, Condition) %>% 
  summarize(correct= mean(Success))%>%
  ungroup()%>%
  group_by(Condition)%>%
  add_count(correct)



con.plot<-ggplot(data=postswitch.agg, aes(x=Condition))+
  #geom_boxplot(alpha=0.5, outlier.colour = "white")+ 
  geom_point(aes(x=Condition, y=correct), alpha=0.5, color="darkgrey", size=postswitch.agg$n)+
  geom_errorbar(data=pred.con.ci$ci.predicted, aes(x=Condition, ymin=lower.cl,ymax=upper.cl), width=0.2)+
  geom_point(data=pred.con.ci$ci.predicted, aes(x=Condition, y=fitted))+
  theme_few()+ylab("Probability of success")+
  ylim(0,1)

con.plot
#ggsave(con.plot, filename="graphs/con_plot.png", height=5, width=6, scale=0.7)

library(cowplot)
pg<-plot_grid(trial.plot, con.plot, labels = c("A", "B"))

ggsave(pg, filename="graphs/trial_and_con_plot.png", height=5, width=10, scale=0.7)
```

```{r}
#save.image("shifting_tray_CI_calc.RData")
```


```{r}
postswitch_stab=glmm.model.stab(model.res=post.mod, contr=contr, para=T)


round(postswitch_stab$summary[, -1], 3)

m.stab.plot(postswitch_stab$summary[,-1])
```

